services:
  - type: web
    name: world-tour
    env: python
    pythonVersion: "3.11.8"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: PYTHON_VERSION
        value: "3.11.8" 