services:
  - type: web
    name: world-tour
    env: python
    pythonVersion: "3.11.8"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here  # Set a strong secret in the Render dashboard
      - key: MAIL_USERNAME
        value: your-email@gmail.com  # Set your real email in the Render dashboard
      - key: MAIL_PASSWORD
        value: your-app-password     # Set your real app password in the Render dashboard
      - key: STRIPE_SECRET_KEY
        value: sk_test_placeholder  # Set your real Stripe secret key in the Render dashboard
      - key: STRIPE_PUBLIC_KEY
        value: pk_test_placeholder  # Set your real Stripe public key in the Render dashboard
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DATABASE_URL
        fromDatabase:
          name: world-tour-db
          property: connectionString
    postDeployCommand: |
      flask db upgrade  # Run migrations after deploy

databases:
  - name: world-tour-db
    databaseName: world_tour
    user: world_tour_user
    plan: free 