import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'fr' | 'sw' | 'es' | 'zh' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.destinations': 'Destinations',
        'nav.hotels': 'Hotels',
        'nav.flights': 'Flights',
        'nav.ai_assistant': 'AI Assistant',
        'nav.login': 'Login',
        'nav.signup': 'Sign Up',
        'nav.logout': 'Logout',
        'hero.subtitle': 'Hand-picked by our experts for your next adventure',
        'btn.book': 'Book Experience',
        'btn.book_now': 'Book Now',
        'btn.search': 'Search',
        'home.destinations.title': 'World Class Destinations',
        'home.destinations.subtitle': 'Hand-picked by our experts for your next adventure',
        'home.map.title': 'Explore the Map',
        'home.map.subtitle': 'Visualise your next journey across the globe',
        'home.cta.title': 'Ready for your next adventure?',
        'home.cta.subtitle': 'Join 50k+ happy travelers and start booking your dream trip today.',
        'hotels.hero.title': 'Luxury Stays',
        'hotels.hero.subtitle': 'Find the perfect accommodation for your journey. From boutique hotels to luxury resorts.',
        'hotels.search.destination': 'Destination',
        'hotels.search.dates': 'Dates',
        'hotels.search.currency': 'Currency',
        'hotels.search.placeholder': 'Where are you going?',
        'hotels.search.dates_placeholder': 'Add dates (Optional)',
        'hotels.card.per_night': '/night',
        'hotels.card.description': 'Luxury accommodation with stunning views and world-class amenities.',
        'hotels.fallback.title': 'No direct partners found for',
        'hotels.fallback.subtitle': 'However, we found excellent options via our trusted partner network.',
        'hotels.fallback.button': 'View Hotels on Booking.com',
        'hotels.empty.message': 'Try searching for "Paris", "Bali", or "Dubai"',
        'common.view_all': 'View All',
        'common.get_started': 'Get Started',
        'common.contact_sales': 'Contact Sales',
        'common.loading': 'Loading...',
        'footer.rights': '© 2026 World Tour. All rights reserved.',
        'footer.privacy': 'Privacy',
        'footer.terms': 'Terms',
        'footer.cookies': 'Cookies',
    },
    fr: {
        'nav.destinations': 'Destinations',
        'nav.hotels': 'Hôtels',
        'nav.flights': 'Vols',
        'nav.ai_assistant': 'Assistant IA',
        'nav.login': 'Connexion',
        'nav.signup': 'S\'inscrire',
        'nav.logout': 'Déconnexion',
        'hero.subtitle': 'Sélectionné par nos experts pour votre prochaine aventure',
        'btn.book': 'Réserver',
        'btn.book_now': 'Réserver Maintenant',
        'btn.search': 'Rechercher',
        'home.destinations.title': 'Destinations de Classe Mondiale',
        'home.destinations.subtitle': 'Sélectionné par nos experts pour votre prochaine aventure',
        'home.map.title': 'Explorer la Carte',
        'home.map.subtitle': 'Visualisez votre prochain voyage à travers le monde',
        'home.cta.title': 'Prêt pour votre prochaine aventure ?',
        'home.cta.subtitle': 'Rejoignez 50k+ voyageurs heureux et commencez à réserver votre voyage de rêve aujourd\'hui.',
        'hotels.hero.title': 'Séjours de Luxe',
        'hotels.hero.subtitle': 'Trouvez l\'hébergement parfait pour votre voyage. Des hôtels boutique aux complexes de luxe.',
        'hotels.search.destination': 'Destination',
        'hotels.search.dates': 'Dates',
        'hotels.search.currency': 'Devise',
        'hotels.search.placeholder': 'Où allez-vous ?',
        'hotels.search.dates_placeholder': 'Ajouter des dates (Optionnel)',
        'hotels.card.per_night': '/nuit',
        'hotels.card.description': 'Hébergement de luxe avec vue imprenable et équipements de classe mondiale.',
        'hotels.fallback.title': 'Aucun partenaire direct trouvé pour',
        'hotels.fallback.subtitle': 'Cependant, nous avons trouvé d\'excellentes options via notre réseau de partenaires de confiance.',
        'hotels.fallback.button': 'Voir les Hôtels sur Booking.com',
        'hotels.empty.message': 'Essayez de rechercher "Paris", "Bali" ou "Dubaï"',
        'common.view_all': 'Voir Tout',
        'common.get_started': 'Commencer',
        'common.contact_sales': 'Contacter les Ventes',
        'common.loading': 'Chargement...',
        'footer.rights': '© 2026 World Tour. Tous droits réservés.',
        'footer.privacy': 'Confidentialité',
        'footer.terms': 'Conditions',
        'footer.cookies': 'Cookies',
    },
    sw: {
        'nav.destinations': 'Vitoe',
        'nav.hotels': 'Hoteli',
        'nav.flights': 'Ndege',
        'nav.ai_assistant': 'Msaidizi wa AI',
        'nav.login': 'Ingia',
        'nav.signup': 'Jisajili',
        'nav.logout': 'Toka',
        'hero.subtitle': 'Imechaguliwa na wataalam wetu kwa safari yako ijayo',
        'btn.book': 'Weka Nafasi',
        'btn.book_now': 'Weka Nafasi Sasa',
        'btn.search': 'Tafuta',
        'home.destinations.title': 'Vitoe vya Hadhi ya Dunia',
        'home.destinations.subtitle': 'Imechaguliwa na wataalam wetu kwa safari yako ijayo',
        'home.map.title': 'Chunguza Ramani',
        'home.map.subtitle': 'Ona safari yako ijayo duniani kote',
        'home.cta.title': 'Uko tayari kwa safari yako ijayo?',
        'home.cta.subtitle': 'Jiunge na wasafiri 50k+ wenye furaha na uanze kuweka nafasi ya safari yako ya ndoto leo.',
        'hotels.hero.title': 'Malazi ya Kifahari',
        'hotels.hero.subtitle': 'Pata malazi kamili kwa safari yako. Kutoka hoteli za boutique hadi vilazimishi vya kifahari.',
        'hotels.search.destination': 'Kitoe',
        'hotels.search.dates': 'Tarehe',
        'hotels.search.currency': 'Sarafu',
        'hotels.search.placeholder': 'Unaenda wapi?',
        'hotels.search.dates_placeholder': 'Ongeza tarehe (Hiari)',
        'hotels.card.per_night': '/usiku',
        'hotels.card.description': 'Malazi ya kifahari yenye mandhari ya kupendeza na vifaa vya hali ya juu.',
        'hotels.fallback.title': 'Hakuna washirika wa moja kwa moja waliopatikana kwa',
        'hotels.fallback.subtitle': 'Hata hivyo, tulipata chaguzi nzuri kupitia mtandao wetu wa washirika wa kuaminika.',
        'hotels.fallback.button': 'Tazama Hoteli kwenye Booking.com',
        'hotels.empty.message': 'Jaribu kutafuta "Paris", "Bali", au "Dubai"',
        'common.view_all': 'Ona Zote',
        'common.get_started': 'Anza Sasa',
        'common.contact_sales': 'Wasiliana na Mauzo',
        'common.loading': 'Inapakia...',
        'footer.rights': '© 2026 World Tour. Haki zote zimehifadhiwa.',
        'footer.privacy': 'Faragha',
        'footer.terms': 'Masharti',
        'footer.cookies': 'Vidakuzi',
    },
    es: {
        'nav.destinations': 'Destinos',
        'nav.hotels': 'Hoteles',
        'nav.flights': 'Vuelos',
        'nav.ai_assistant': 'Asistente IA',
        'nav.login': 'Entrar',
        'nav.signup': 'Registrarse',
        'nav.logout': 'Salir',
        'hero.subtitle': 'Seleccionado por nuestros expertos para tu próxima aventura',
        'btn.book': 'Reservar',
        'btn.book_now': 'Reservar Ahora',
        'btn.search': 'Buscar',
        'home.destinations.title': 'Destinos de Clase Mundial',
        'home.destinations.subtitle': 'Seleccionado por nuestros expertos para tu próxima aventura',
        'home.map.title': 'Explorar el Mapa',
        'home.map.subtitle': 'Visualiza tu próximo viaje por todo el mundo',
        'home.cta.title': '¿Listo para tu próxima aventura?',
        'home.cta.subtitle': 'Únete a más de 50k viajeros felices y comienza a reservar el viaje de tus sueños hoy.',
        'hotels.hero.title': 'Estancias de Lujo',
        'hotels.hero.subtitle': 'Encuentra el alojamiento perfecto para tu viaje. Desde hoteles boutique hasta resorts de lujo.',
        'hotels.search.destination': 'Destino',
        'hotels.search.dates': 'Fechas',
        'hotels.search.currency': 'Moneda',
        'hotels.search.placeholder': '¿A dónde vas?',
        'hotels.search.dates_placeholder': 'Agregar fechas (Opcional)',
        'hotels.card.per_night': '/noche',
        'hotels.card.description': 'Alojamiento de lujo con vistas impresionantes y comodidades de clase mundial.',
        'hotels.fallback.title': 'No se encontraron socios directos para',
        'hotels.fallback.subtitle': 'Sin embargo, encontramos excelentes opciones a través de nuestra red de socios de confianza.',
        'hotels.fallback.button': 'Ver Hoteles en Booking.com',
        'hotels.empty.message': 'Intenta buscar "París", "Bali" o "Dubái"',
        'common.view_all': 'Ver Todo',
        'common.get_started': 'Empezar',
        'common.contact_sales': 'Contactar Ventas',
        'common.loading': 'Cargando...',
        'footer.rights': '© 2026 World Tour. Todos los derechos reservados.',
        'footer.privacy': 'Privacidad',
        'footer.terms': 'Términos',
        'footer.cookies': 'Cookies',
    },
    zh: {
        'nav.destinations': '目的地',
        'nav.hotels': '酒店',
        'nav.flights': '航班',
        'nav.ai_assistant': 'AI 助手',
        'nav.login': '登录',
        'nav.signup': '注册',
        'nav.logout': '登出',
        'hero.subtitle': '由我们的专家为您挑选的下一次冒险',
        'btn.book': '预订体验',
        'btn.book_now': '立即预订',
        'btn.search': '搜索',
        'home.destinations.title': '世界级目的地',
        'home.destinations.subtitle': '由我们的专家为您挑选的下一次冒险',
        'home.map.title': '探索地图',
        'home.map.subtitle': '可视化您在全球的下一次旅程',
        'home.cta.title': '准备好下一次冒险了吗？',
        'home.cta.subtitle': '加入50k+快乐的旅行者，今天就开始预订您的梦想之旅。',
        'hotels.hero.title': '豪华住宿',
        'hotels.hero.subtitle': '为您的旅程找到完美的住宿。从精品酒店到豪华度假村。',
        'hotels.search.destination': '目的地',
        'hotels.search.dates': '日期',
        'hotels.search.currency': '货币',
        'hotels.search.placeholder': '你要去哪里？',
        'hotels.search.dates_placeholder': '添加日期（可选）',
        'hotels.card.per_night': '/晚',
        'hotels.card.description': '豪华住宿，拥有令人惊叹的景色和世界一流的设施。',
        'hotels.fallback.title': '未找到直接合作伙伴',
        'hotels.fallback.subtitle': '但是，我们通过我们值得信赖的合作伙伴网络找到了出色的选择。',
        'hotels.fallback.button': '在Booking.com上查看酒店',
        'hotels.empty.message': '尝试搜索"巴黎"、"巴厘岛"或"迪拜"',
        'common.view_all': '查看全部',
        'common.get_started': '开始',
        'common.contact_sales': '联系销售',
        'common.loading': '加载中...',
        'footer.rights': '© 2026 World Tour. 保留所有权利。',
        'footer.privacy': '隐私',
        'footer.terms': '条款',
        'footer.cookies': 'Cookies',
    },
    ar: {
        'nav.destinations': 'الوجهات',
        'nav.hotels': 'فنادق',
        'nav.flights': 'رحلات طيران',
        'nav.ai_assistant': 'مساعد الذكاء الاصطناعي',
        'nav.login': 'تسجيل الدخول',
        'nav.signup': 'التسجيل',
        'nav.logout': 'تسجيل الخروج',
        'hero.subtitle': 'تم اختيارها بعناية من قبل خبرائنا لمغامرتك القادمة',
        'btn.book': 'احجز التجربة',
        'btn.book_now': 'احجز الآن',
        'btn.search': 'يتحرى',
        'home.destinations.title': 'وجهات عالمية المستوى',
        'home.destinations.subtitle': 'تم اختيارها بعناية من قبل خبرائنا لمغامرتك القادمة',
        'home.map.title': 'اكتشف الخريطة',
        'home.map.subtitle': 'تصور رحلتك القادمة حول العالم',
        'home.cta.title': 'هل أنت مستعد لمغامرتك القادمة؟',
        'home.cta.subtitle': 'انضم إلى أكثر من 50 ألف مسافر سعيد وابدأ في حجز رحلة أحلامك اليوم.',
        'hotels.hero.title': 'إقامات فاخرة',
        'hotels.hero.subtitle': 'ابحث عن الإقامة المثالية لرحلتك. من الفنادق البوتيكية إلى المنتجعات الفاخرة.',
        'hotels.search.destination': 'الوجهة',
        'hotels.search.dates': 'التواريخ',
        'hotels.search.currency': 'العملة',
        'hotels.search.placeholder': 'إلى أين تذهب؟',
        'hotels.search.dates_placeholder': 'إضافة تواريخ (اختياري)',
        'hotels.card.per_night': '/ليلة',
        'hotels.card.description': 'إقامة فاخرة مع مناظر خلابة ووسائل راحة عالمية المستوى.',
        'hotels.fallback.title': 'لم يتم العثور على شركاء مباشرين لـ',
        'hotels.fallback.subtitle': 'ومع ذلك، وجدنا خيارات ممتازة عبر شبكة شركائنا الموثوقين.',
        'hotels.fallback.button': 'عرض الفنادق على Booking.com',
        'hotels.empty.message': 'حاول البحث عن "باريس" أو "بالي" أو "دبي"',
        'common.view_all': 'عرض الكل',
        'common.get_started': 'البدء',
        'common.contact_sales': 'اتصل بالمبيعات',
        'common.loading': 'جار التحميل...',
        'footer.rights': '© 2026 World Tour. جميع الحقوق محفوظة.',
        'footer.privacy': 'الخصوصية',
        'footer.terms': 'الشروط',
        'footer.cookies': 'ملفات تعريف الارتباط',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
